lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
  dashboards:
    dashy-mcdashboardface:
      mode: yaml
      title: Dashy McDashboardface
      icon: mdi:view-dashboard
      show_in_sidebar: true
      filename: www/community/ha-dashy-mcdashboardface/home.yaml
