title: Home
views:
  - title: Overview
    path: home
    type: sidebar
    cards:
      - type: custom:auto-entities
        columns: 4
        square: false
        card_param: cards
        filter:
          include:
            - domain: person
        sort:
          method: friendly_name
        template: >-
          {{
            {
              "type": "custom:mushroom-person-card",
              "entity": entity,
              "layout": "vertical",
              "primary_info": "name",
              "secondary_info": "state"
            }
          }}
